/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.Orientation;
import Classes.Subject;
import Classes.Year;
import Utils.Combo;
import java.text.ParseException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author acer
 */
public class ModifySubject extends javax.swing.JFrame {

  /**
   * Creates new form LoadSubject
   */
  public ModifySubject() {
      initComponents();
      changeBoxs();
      disableButtons();
  }
    
  LoadSubject loadSubject;
  ArrayList subjscod;
  /**
   * This method is called from within the constructor to initialize the form.
   * WARNING: Do NOT modify this code. The content of this method is always
   * regenerated by the Form Editor.
   */
  @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel1 = new javax.swing.JLabel();
    jLabel3 = new javax.swing.JLabel();
    jLabel4 = new javax.swing.JLabel();
    yearBox = new javax.swing.JComboBox();
    jLabel5 = new javax.swing.JLabel();
    orientationBox = new javax.swing.JComboBox();
    exitLoadSubject = new javax.swing.JButton();
    typeBox = new javax.swing.JComboBox<>();
    jLabel6 = new javax.swing.JLabel();
    jToggleButton1 = new javax.swing.JToggleButton();
    subjscodBox = new javax.swing.JComboBox<>();
    jLabel7 = new javax.swing.JLabel();
    nameField = new javax.swing.JTextField();
    jLabel8 = new javax.swing.JLabel();
    deleteButton = new javax.swing.JButton();
    saveButton = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);
    addWindowListener(new java.awt.event.WindowAdapter() {
      public void windowActivated(java.awt.event.WindowEvent evt) {
        formWindowActivated(evt);
      }
      public void windowClosed(java.awt.event.WindowEvent evt) {
        formWindowClosed(evt);
      }
    });

    jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
    jLabel1.setText("Editar materia");

    jLabel3.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
    jLabel3.setText("Determine los siguientes datos:");

    jLabel4.setText("Año:");

    yearBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "           ", "Primero", "Segundo", "Tercero", "Cuarto", "Quinto", "Sexto", "Séptimo" }));
    yearBox.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        yearBoxItemStateChanged(evt);
      }
    });

    jLabel5.setText("Orientación:");

    orientationBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "           ", "General", "Informática", "Electromecánica" }));
    orientationBox.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        orientationBoxItemStateChanged(evt);
      }
    });
    orientationBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        orientationBoxActionPerformed(evt);
      }
    });

    exitLoadSubject.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    exitLoadSubject.setText("SALIR");
    exitLoadSubject.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        exitLoadSubjectActionPerformed(evt);
      }
    });

    typeBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "                                             ", "Formación General", "Formación Técnica Específica" }));
    typeBox.addItemListener(new java.awt.event.ItemListener() {
      public void itemStateChanged(java.awt.event.ItemEvent evt) {
        typeBoxItemStateChanged(evt);
      }
    });
    typeBox.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        typeBoxActionPerformed(evt);
      }
    });

    jLabel6.setText("Categoria:");

    jToggleButton1.setText("BUSCAR");
    jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jToggleButton1ActionPerformed(evt);
      }
    });

    jLabel7.setText("Materia");

    jLabel8.setText("Nombre:");

    deleteButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    deleteButton.setText("ELIMINAR");
    deleteButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        deleteButtonActionPerformed(evt);
      }
    });

    saveButton.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
    saveButton.setText("GUARDAR");
    saveButton.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        saveButtonActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(21, 21, 21)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel4)
                    .addGap(0, 0, Short.MAX_VALUE))
                  .addComponent(yearBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(orientationBox, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                  .addComponent(jLabel5)))
              .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                  .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                  .addComponent(typeBox, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 177, Short.MAX_VALUE)))
            .addContainerGap())
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jToggleButton1)
            .addGap(16, 16, 16))))
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel8)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
              .addComponent(jLabel7)
              .addComponent(subjscodBox, 0, 177, Short.MAX_VALUE)
              .addComponent(nameField))
            .addGap(142, 142, 142))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(deleteButton)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(exitLoadSubject, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addContainerGap())))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(19, 19, 19)
        .addComponent(jLabel1)
        .addGap(18, 18, 18)
        .addComponent(jLabel3)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel4)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(yearBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(orientationBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
          .addGroup(layout.createSequentialGroup()
            .addComponent(jLabel6)
            .addGap(26, 26, 26))
          .addComponent(typeBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        .addGap(21, 21, 21)
        .addComponent(jToggleButton1)
        .addGap(11, 11, 11)
        .addComponent(jLabel7)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(subjscodBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
          .addComponent(jLabel8))
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
          .addComponent(exitLoadSubject)
          .addComponent(deleteButton)
          .addComponent(saveButton))
        .addContainerGap())
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

    private void orientationBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orientationBoxActionPerformed
        
    }//GEN-LAST:event_orientationBoxActionPerformed

    private void exitLoadSubjectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitLoadSubjectActionPerformed
      loadSubject.setVisible(true);
      dispose();
    }//GEN-LAST:event_exitLoadSubjectActionPerformed

  private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
    
  }//GEN-LAST:event_formWindowActivated

  private void typeBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_typeBoxActionPerformed
    // TODO add your handling code here:
  }//GEN-LAST:event_typeBoxActionPerformed

  private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
    if (checkEmptyFields()) return;
    if (!Year.checkYear(yearBox.getSelectedItem().toString(), orientationBox.getSelectedItem().toString())) {
      JOptionPane.showMessageDialog(null, "Los datos ingresados del año y la orientación son incorrectos");
      return;
    }
    if (!Subject.checkType(typeBox.getSelectedItem().toString())) {
      JOptionPane.showMessageDialog(null, "El tipo de matería no existe");
      return;
    }
    
    int oricod = Orientation.getOrientationcod(orientationBox.getSelectedItem().toString());
    
    subjscod = Subject.getSubjectsCodByCourseAndCategory(oricod, Year.getYearcod(yearBox.getSelectedItem().toString(), oricod), Subject.getTypeCodeByName(typeBox.getSelectedItem().toString()));
    
    subjscodBox.removeAllItems();
    
    subjscod.forEach(subcod -> {
      subjscodBox.addItem(Subject.getSubjectNameByCode((int) subcod));
    });
    
    if(subjscod.size() > 0) {
      JOptionPane.showMessageDialog(null, "La lista de materias ha sido actualizada");
      enableButtons();
    } else {
      JOptionPane.showMessageDialog(null, "No se han encontrado materias");
      disableButtons();
    }
    
  }//GEN-LAST:event_jToggleButton1ActionPerformed

  private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
    if(!(JOptionPane.showConfirmDialog(null, "Está seguro de eliminarla?") == 0)) return;
    try {
      if(Subject.removeSubject((int) subjscod.get(subjscodBox.getSelectedIndex()))) {
        JOptionPane.showMessageDialog(null, "La materia fue fue eliminado");
        loadSubject.setVisible(true);
        dispose();
      } else {
        JOptionPane.showMessageDialog(null, "Se ha producido un error, nada fue eliminado");
      }
    } catch (ParseException ex) {
      Logger.getLogger(ModifySubject.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_deleteButtonActionPerformed

  private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
    if(!(JOptionPane.showConfirmDialog(null, "Está seguro de guardar?") == 0)) return;
    try {
      if(Subject.changeSubjectName((int) subjscod.get(subjscodBox.getSelectedIndex()), nameField.getText())){
        JOptionPane.showMessageDialog(null, "Se ha modificado la materia");
        loadSubject.setVisible(true);
        dispose();
      } else {
        JOptionPane.showMessageDialog(null, "Se ha producido un error inesperado");
      }
    } catch (ParseException ex) {
      Logger.getLogger(ModifySubject.class.getName()).log(Level.SEVERE, null, ex);
    }
  }//GEN-LAST:event_saveButtonActionPerformed

  private void yearBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_yearBoxItemStateChanged
    disableButtons();
  }//GEN-LAST:event_yearBoxItemStateChanged

  private void orientationBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_orientationBoxItemStateChanged
    disableButtons();
  }//GEN-LAST:event_orientationBoxItemStateChanged

  private void typeBoxItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_typeBoxItemStateChanged
    disableButtons();
  }//GEN-LAST:event_typeBoxItemStateChanged

  private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
    loadSubject.setVisible(true);
  }//GEN-LAST:event_formWindowClosed

    
  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton deleteButton;
  private javax.swing.JButton exitLoadSubject;
  private javax.swing.JLabel jLabel1;
  private javax.swing.JLabel jLabel3;
  private javax.swing.JLabel jLabel4;
  private javax.swing.JLabel jLabel5;
  private javax.swing.JLabel jLabel6;
  private javax.swing.JLabel jLabel7;
  private javax.swing.JLabel jLabel8;
  private javax.swing.JToggleButton jToggleButton1;
  private javax.swing.JTextField nameField;
  private javax.swing.JComboBox orientationBox;
  private javax.swing.JButton saveButton;
  private javax.swing.JComboBox<String> subjscodBox;
  private javax.swing.JComboBox<String> typeBox;
  private javax.swing.JComboBox yearBox;
  // End of variables declaration//GEN-END:variables

  private boolean checkEmptyFields() {
    if(yearBox.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Indique el año");
    } else if(orientationBox.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Indique la orientación");
    } else if (typeBox.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Ingrese el tipo");
    } else {
      return false;
    }

    return true;
  }

  void changeBoxs() {
    Combo.setComboBoxItems(Year.getYears(false), yearBox);
    Combo.setComboBoxItems(Orientation.getOrientations(false), orientationBox);
    Combo.setComboBoxItems(Subject.getTypes(), typeBox);
  }

  private void disableButtons() {
    saveButton.setEnabled(false);
    deleteButton.setEnabled(false);
  }

  private void enableButtons() {
    saveButton.setEnabled(true);
    deleteButton.setEnabled(true);
  }

}
