/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Forms;

import Classes.Categorie;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author lagos
 */
public class SelectCategorie extends javax.swing.JFrame {

    /**
     * Creates new form changePassword
     */
  public SelectCategorie() {
    initComponents();
  }
    
  Menu menu;
  boolean seeNote = false;
  boolean seeCourse = false;
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jLabel5 = new javax.swing.JLabel();
    combo = new javax.swing.JComboBox<>();
    jButton1 = new javax.swing.JButton();
    jButton2 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    setResizable(false);

    jLabel5.setText("Seleccione la categoria con la que quiere ingresar:");

    jButton1.setText("SELECCIONAR");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    jButton2.setText("SALIR");
    jButton2.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton2ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap(47, Short.MAX_VALUE)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(jLabel5)
            .addGap(54, 54, 54))
          .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
            .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(45, 45, 45))))
      .addGroup(layout.createSequentialGroup()
        .addGap(136, 136, 136)
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
          .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
          .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        .addGap(0, 0, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addGap(35, 35, 35)
        .addComponent(jLabel5)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
        .addComponent(combo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        .addGap(18, 18, 18)
        .addComponent(jButton1)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton2)
        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
  }// </editor-fold>//GEN-END:initComponents

  private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    dispose();
  }//GEN-LAST:event_jButton2ActionPerformed

  private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    if(combo.getSelectedIndex() == 0) {
      JOptionPane.showMessageDialog(null, "Seleccione una categoria");
    } else if (!combo.getSelectedItem().toString().equals("Alumno") && !combo.getSelectedItem().toString().equals("Profesor") && !combo.getSelectedItem().toString().equals("Administrador") && seeNote == true) {
      JOptionPane.showMessageDialog(null, "La categoria seleccionada no tiene los permisos suficentes");
    } else if (seeNote == true) {
      SeeNote seeNote = new SeeNote();
      seeNote.menu = menu;
      seeNote.userType = combo.getSelectedItem().toString();
      seeNote.changeBoxs();
      seeNote.setVisible(true);
      menu.setVisible(false);
      dispose();
    } else if (seeCourse == true) {
      SeeCourse seeCourse = new SeeCourse();
      seeCourse.menu = menu;
      seeCourse.userType = combo.getSelectedItem().toString();
      seeCourse.changeBoxs();
      seeCourse.setVisible(true);
      menu.setVisible(false);
      dispose();
    }
  }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JComboBox<String> combo;
  private javax.swing.JButton jButton1;
  private javax.swing.JButton jButton2;
  private javax.swing.JLabel jLabel5;
  // End of variables declaration//GEN-END:variables

  public void updateCombo(ArrayList categories) {
    combo.addItem("");
    
    categories.forEach(categorie -> {
      combo.addItem(Categorie.getCatName((int) categorie));
    });
  }

  
   
}
